/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.marlevous.sparen.swing;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.table.TableColumn;

/**
 *
 * @author Note201
 */
public class RekeningenFormulier extends javax.swing.JFrame {

    /**
     * Creates new form RekeningenFormulier
     */
    public RekeningenFormulier(RekeningenTableModel rekeningenModel) {
        initComponents();
        this.RekeningenTabel.setModel(rekeningenModel);
        RekeningenTabel.getColumnModel().getColumn(2).setCellRenderer(
                new BedragCellRenderer());
        RekeningenTabel.changeSelection(0, 0, false, false);
        RekeningenTabel.getColumnModel().getColumn(0).setMaxWidth(40);

        //totaalSaldo.setText(String.format("%.2f", rekeningenModel.totaalSaldo()));
        totaalSaldo.setValue(rekeningenModel.totaalSaldo());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RekeningenTabel = new javax.swing.JTable();
        Locale l = new Locale("nl", "NL");
        NumberFormat nf = NumberFormat.getCurrencyInstance(l);
        totaalSaldo = new javax.swing.JFormattedTextField(nf)
        ;
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rekeningen");
        setLocationByPlatform(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                doResize(evt);
            }
        });

        RekeningenTabel.setAutoCreateRowSorter(true);
        RekeningenTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        RekeningenTabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(RekeningenTabel);

        totaalSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setText("Totaal saldo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totaalSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaalSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doResize(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_doResize
        this.RekeningenTabel.doLayout();
    }//GEN-LAST:event_doResize

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RekeningenTabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField totaalSaldo;
    // End of variables declaration//GEN-END:variables
}
