package nl.marlevous.sparen.swing;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import java.util.Formatter;
import java.util.Locale;
import javax.swing.JFrame;
import nl.marlevous.sparen.Spaarpotten;

/**
 *
 * @author Note201
 */
public class SpaarpottenFormulier extends javax.swing.JFrame {

    SpaarpottenTableModel myModel;
    Spaarpotten spaarpotten;

    /**
     * Creates new form RekeningenFormulier
     */
    public SpaarpottenFormulier() {
        spaarpotten = Spaarpotten.leesSpaarpotten();
        myModel = new SpaarpottenTableModel(spaarpotten);
        initComponents();
        this.spaarpottenTabel.setModel(myModel);
        spaarpottenTabel.getColumnModel().getColumn(2).setCellRenderer(
                new BedragCellRenderer());
        spaarpottenTabel.getColumnModel().getColumn(3).setCellRenderer(
                new BedragCellRenderer());

        spaarpottenTabel.changeSelection(0, 0, false, false);
        spaarpottenTabel.getColumnModel().getColumn(0).setMaxWidth(40);

        this.spaarpottenTabel.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int xLoc = e.getXOnScreen() + 20;
                    int yLoc = e.getYOnScreen() + 20;
                    int row = spaarpottenTabel.getSelectedRow();
                    if (row != -1) {
                        long spaarpot = (long) spaarpottenTabel.getModel().getValueAt(row, 0);
                        SpaarpotEditor editor = new SpaarpotEditor(
                                spaarpot,
                                new JFrame(),
                                true,
                                xLoc,
                                yLoc);
                        editor.setVisible(true);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        spaarpottenTabel = new javax.swing.JTable();
        lblBalans = new javax.swing.JLabel();
        btnNieuw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Spaarpotten");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                doResize(evt);
            }
        });

        spaarpottenTabel.setAutoCreateRowSorter(true);
        spaarpottenTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        spaarpottenTabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(spaarpottenTabel);

        lblBalans.setForeground(new java.awt.Color(204, 51, 0));
        lblBalans.setText("jLabel1");

        btnNieuw.setText("Nieuwe spaarpot");
        btnNieuw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNieuwActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBalans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNieuw)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNieuw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBalans)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doResize(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_doResize
        this.spaarpottenTabel.doLayout();
    }//GEN-LAST:event_doResize

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        spaarpotten = Spaarpotten.leesSpaarpotten();
        myModel.setSpaarpotten(spaarpotten);
        double balans = spaarpotten.standaardBalans();
        Locale l = new Locale("nl", "NL");
        NumberFormat f = NumberFormat.getCurrencyInstance(l);
        String bedrag = f.format(Math.abs(balans));

        if (balans != 0.0) {
            if (balans < 0.0) {
                lblBalans.setText(String.format("Standaarden zijn %s te laag.", bedrag));
                lblBalans.setVisible(true);
            }
            if (balans > 0.0) {
                lblBalans.setText(String.format("Standaarden zijn %s te hoog.", bedrag));
                lblBalans.setVisible(true);
            }
        } else {
            lblBalans.setVisible(false);
        }
 }//GEN-LAST:event_formWindowActivated

    private void btnNieuwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNieuwActionPerformed
        int xLoc = btnNieuw.getX() + 20;
        int yLoc = btnNieuw.getY();
        SpaarpotEditor editor = new SpaarpotEditor(
                0,
                new JFrame(),
                true,
                xLoc,
                yLoc);
        editor.setVisible(true);

    }//GEN-LAST:event_btnNieuwActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNieuw;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBalans;
    private javax.swing.JTable spaarpottenTabel;
    // End of variables declaration//GEN-END:variables
}
