package nl.marlevous.sparen.swing;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;
import nl.marlevous.sparen.Spaarpot;
import nl.marlevous.sparen.database.SpaarpotDAO;

/**
 *
 * @author Leo
 */
public class SpaarpotEditor extends javax.swing.JDialog {

    private Spaarpot spaarpot;

    class StandaardValueListener implements PropertyChangeListener {

        Double value = null;

        public Double getValue() {
            return value;
        }

        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            if ("value".equals(evt.getPropertyName())) {
                if (evt.getSource() == fldStandaard) {
                    if (evt.getNewValue() != evt.getOldValue()) {
                        this.value = ((Number) evt.getNewValue()).doubleValue();
                    }
                }
            }
        }
    }

    class NaamListener implements DocumentListener {

        String naam;
        boolean changed = false;

        public NaamListener(String naam) {
            this.naam = naam;
        }

        public boolean isChanged() {
            return changed;
        }

        public String getNaam() {
            return naam;
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            recordChange(e);
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            recordChange(e);
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            recordChange(e);
        }

        private void recordChange(DocumentEvent e) {
            int len = e.getDocument().getLength();
            try {
                String nieuweNaam = e.getDocument().getText(0, len);
                if (!nieuweNaam.equals(this.naam)) {
                    this.naam = nieuweNaam;
                    this.changed = true;
                }
            } catch (BadLocationException ex) {
                Logger.getLogger(SpaarpotEditor.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }
    private StandaardValueListener standaardValueListener = new StandaardValueListener();
    private NaamListener naamListener;

    public SpaarpotEditor(long spaarpotID, java.awt.Frame parent, boolean modal, int xLocation, int yLocation) {
        super(parent, modal);
        if (spaarpotID != 0) {
            this.spaarpot = SpaarpotDAO.leesSpaarpot(spaarpotID);
        } else {
            this.spaarpot = new Spaarpot();
        }
        this.naamListener = new NaamListener(this.spaarpot.naam());
        initComponents();
        // this.fldStandaard.setVisible(spaarpot.heeftStandaard());
        this.setLocation(xLocation, yLocation);
        this.txtNaam.setText(spaarpot.naam());
        this.cbStandaard.setSelected(spaarpot.heeftStandaard());
        if (spaarpot.heeftStandaard()) {
            fldStandaard.setValue(spaarpot.getStandaard());
        }

        // bind listener
        fldStandaard.addPropertyChangeListener("value", standaardValueListener);
        txtNaam.getDocument().addDocumentListener(naamListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtNaam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbStandaard = new javax.swing.JCheckBox();
        fldStandaard = new formattedfields.FormattedCurrencyField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wijzig spaarpot");

        jButton1.setText("Sla op");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Naam");

        cbStandaard.setText("Standaard gedefinieerd");
        cbStandaard.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbStandaardStateChanged(evt);
            }
        });

        fldStandaard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 226, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2))
                    .addComponent(txtNaam)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbStandaard)
                        .addGap(18, 18, 18)
                        .addComponent(fldStandaard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStandaard)
                    .addComponent(fldStandaard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbStandaardStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbStandaardStateChanged
        if (cbStandaard.isSelected()) {
            fldStandaard.setVisible(true);
            this.spaarpot.setHeeftStandaard(true);
        } else {
            fldStandaard.setVisible(false);
            this.spaarpot.setHeeftStandaard(false);
        }
    }//GEN-LAST:event_cbStandaardStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Collect the changes
        if (standaardValueListener.getValue() != null) {
            spaarpot.setStandaard(standaardValueListener.getValue());
            spaarpot.setHeeftStandaard(true);
        }
        if (naamListener.isChanged()) {
            spaarpot.setNaam(naamListener.getNaam());

        }
        spaarpot.slaop();
        setVisible(false);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbStandaard;
    private formattedfields.FormattedCurrencyField fldStandaard;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNaam;
    // End of variables declaration//GEN-END:variables
}
