
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

/*
 * FormattedTextFeildDemo.java
 *
 * Created on March 31, 2009, 3:41 PM
 */
/**
 *
 * @author Mark Pendergast Copyright Mark Pendergast
 */
public class FormattedTextFeildDemo extends javax.swing.JFrame {

    public static void showLocales() {
        // Print out a number using the localized number, integer, currency,
        // and percent format for each locale
        String localeString = java.util.Locale.getDefault().getDisplayName();
        System.out.printf("Locale: %s\n\n", localeString);
        Locale[] locales = NumberFormat.getAvailableLocales();
        double myNumber = -1234.56;
        NumberFormat form;
        for (int j = 0; j < 4; ++j) {
            System.out.println("FORMAT");
            for (int i = 0; i < locales.length; ++i) {
                if (locales[i].getCountry().length() == 0) {
                    continue; // Skip language-only locales
                }
                System.out.print(locales[i].getDisplayName());
                System.out.print(" Country: " + locales[i].getCountry() + " Language: " + locales[i].getLanguage());
                switch (j) {
                    case 0:
                        form = NumberFormat.getInstance(locales[i]);
                        break;
                    case 1:
                        form = NumberFormat.getIntegerInstance(locales[i]);
                        break;
                    case 2:
                        form = NumberFormat.getCurrencyInstance(locales[i]);
                        break;
                    default:
                        form = NumberFormat.getPercentInstance(locales[i]);
                        break;
                }
                if (form instanceof DecimalFormat) {
                    System.out.print(": " + ((DecimalFormat) form).toPattern());
                }
                System.out.print(" -> " + form.format(myNumber));
                try {
                    System.out.println(" -> " + form.parse(form.format(myNumber)));
                } catch (ParseException e) {
                }
            }
        }
    }

  
    /**
     * Creates new form FormattedTextFeildDemo
     */
    public FormattedTextFeildDemo() {
        showLocales();
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        doublePanel = new javax.swing.JPanel();
        xField = new formattedfields.FormattedDoubleField();
        yField = new formattedfields.FormattedDoubleField();
        zField = new formattedfields.FormattedDoubleField();
        addButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        annuityPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        periodsField = new formattedfields.FormattedIntegerField();
        rateField = new formattedfields.FormattedPercentField();
        fvField = new formattedfields.FormattedCurrencyField();
        paymentField = new formattedfields.FormattedCurrencyField();
        formattedCurrencyField2 = new formattedfields.FormattedCurrencyField();
        exitButton = new javax.swing.JButton();
        integerPanel = new javax.swing.JPanel();
        iXField = new formattedfields.FormattedIntegerField();
        iYField = new formattedfields.FormattedIntegerField();
        iZField = new formattedfields.FormattedIntegerField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        integerAddButton = new javax.swing.JButton();
        dataPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        try {
            phoneField = new formattedfields.FormattedPhoneField();
        } catch (java.text.ParseException e1) {
            e1.printStackTrace();
        }
        emailField = new formattedfields.FormattedEmailField();
        try {
            ssnField = new formattedfields.FormattedSSNField();
        } catch (java.text.ParseException e1) {
            e1.printStackTrace();
        }
        jLabel7 = new javax.swing.JLabel();
        try {
            dateField = new formattedfields.FormattedDateField();
        } catch (java.text.ParseException e1) {
            e1.printStackTrace();
        }
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JFormattedTextField Demo");

        centerPanel.setPreferredSize(new java.awt.Dimension(640, 425));
        centerPanel.setRequestFocusEnabled(false);
        centerPanel.setLayout(null);

        doublePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("JFormattedDoubleFields"));
        doublePanel.setLayout(null);

        xField.setColumns(10);
        doublePanel.add(xField);
        xField.setBounds(90, 30, 90, 20);

        yField.setColumns(10);
        doublePanel.add(yField);
        yField.setBounds(90, 60, 90, 20);
        doublePanel.add(zField);
        zField.setBounds(90, 100, 90, 20);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        doublePanel.add(addButton);
        addButton.setBounds(10, 100, 60, 23);

        jLabel2.setText("Y: ");
        doublePanel.add(jLabel2);
        jLabel2.setBounds(20, 60, 40, 14);

        jLabel1.setText("X:");
        doublePanel.add(jLabel1);
        jLabel1.setBounds(20, 30, 30, 14);

        centerPanel.add(doublePanel);
        doublePanel.setBounds(20, 20, 210, 160);

        annuityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Future Value Annuity Calculator"));
        annuityPanel.setLayout(null);

        jLabel3.setText("Interest Rate: ");
        annuityPanel.add(jLabel3);
        jLabel3.setBounds(40, 30, 90, 20);

        jLabel4.setText("Periodic Payment: ");
        annuityPanel.add(jLabel4);
        jLabel4.setBounds(40, 60, 110, 14);

        jLabel5.setText("Periods: ");
        annuityPanel.add(jLabel5);
        jLabel5.setBounds(40, 90, 90, 14);

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });
        annuityPanel.add(calculateButton);
        calculateButton.setBounds(40, 120, 90, 23);

        periodsField.setMaxValue(400);
        periodsField.setMinValue(0);
        annuityPanel.add(periodsField);
        periodsField.setBounds(160, 90, 70, 20);

        rateField.setMaxValue(500.0);
        rateField.setMinValue(0.0);
        annuityPanel.add(rateField);
        rateField.setBounds(160, 30, 70, 20);
        annuityPanel.add(fvField);
        fvField.setBounds(160, 120, 70, 20);

        paymentField.setMaxValue(1000000.0);
        paymentField.setMinValue(0.0);
        annuityPanel.add(paymentField);
        paymentField.setBounds(160, 60, 70, 20);

        formattedCurrencyField2.setCountry("US");
        formattedCurrencyField2.setLanguage("en");
        annuityPanel.add(formattedCurrencyField2);
        formattedCurrencyField2.setBounds(250, 120, 90, 20);

        centerPanel.add(annuityPanel);
        annuityPanel.setBounds(260, 20, 350, 160);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        centerPanel.add(exitButton);
        exitButton.setBounds(490, 370, 80, 23);

        integerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("JFormattedIntegerFields"));
        integerPanel.setLayout(null);

        iXField.setColumns(6);
        integerPanel.add(iXField);
        iXField.setBounds(90, 30, 90, 20);

        iYField.setColumns(6);
        integerPanel.add(iYField);
        iYField.setBounds(90, 60, 90, 20);

        iZField.setColumns(6);
        integerPanel.add(iZField);
        iZField.setBounds(90, 100, 90, 20);

        jLabel9.setText("X:");
        integerPanel.add(jLabel9);
        jLabel9.setBounds(20, 30, 40, 14);

        jLabel10.setText("Y: ");
        integerPanel.add(jLabel10);
        jLabel10.setBounds(20, 60, 13, 14);

        integerAddButton.setText("Add");
        integerAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                integerAddButtonActionPerformed(evt);
            }
        });
        integerPanel.add(integerAddButton);
        integerAddButton.setBounds(10, 100, 60, 23);

        centerPanel.add(integerPanel);
        integerPanel.setBounds(20, 200, 210, 160);

        dataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Fields"));
        dataPanel.setLayout(null);

        jLabel6.setText("Phone:");
        dataPanel.add(jLabel6);
        jLabel6.setBounds(10, 30, 80, 14);

        jLabel8.setText("Email: ");
        dataPanel.add(jLabel8);
        jLabel8.setBounds(10, 90, 70, 14);

        phoneField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        dataPanel.add(phoneField);
        phoneField.setBounds(160, 30, 120, 23);

        emailField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        dataPanel.add(emailField);
        emailField.setBounds(160, 90, 190, 23);

        ssnField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        dataPanel.add(ssnField);
        ssnField.setBounds(160, 60, 94, 23);

        jLabel7.setText("Social Security Number:");
        dataPanel.add(jLabel7);
        jLabel7.setBounds(10, 60, 140, 14);

        dateField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        dataPanel.add(dateField);
        dateField.setBounds(160, 120, 190, 23);

        jLabel11.setText("Date :");
        dataPanel.add(jLabel11);
        jLabel11.setBounds(10, 120, 80, 14);

        centerPanel.add(dataPanel);
        dataPanel.setBounds(250, 200, 360, 160);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

    Double x = (Double) xField.getValue();
    Double y = (Double) yField.getValue();
    zField.setValue(new Double(x + y));
}//GEN-LAST:event_addButtonActionPerformed

private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
    Double rate = (Double) rateField.getValue();
    Double payment = (Double) paymentField.getValue();
    Integer periods = (Integer) periodsField.getValue();

    Double fv = payment * (Math.pow(1 + rate, periods) - 1) / rate;
    fvField.setValue(new Double(fv));
}//GEN-LAST:event_calculateButtonActionPerformed

private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
    System.exit(0);
}//GEN-LAST:event_exitButtonActionPerformed

private void integerAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_integerAddButtonActionPerformed

    Integer x = (Integer) iXField.getValue();
    Integer y = (Integer) iYField.getValue();
    iZField.setValue(new Integer(x + y));
}//GEN-LAST:event_integerAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormattedTextFeildDemo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel annuityPanel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel dataPanel;
    private formattedfields.FormattedDateField dateField;
    private javax.swing.JPanel doublePanel;
    private formattedfields.FormattedEmailField emailField;
    private javax.swing.JButton exitButton;
    private formattedfields.FormattedCurrencyField formattedCurrencyField2;
    private formattedfields.FormattedCurrencyField fvField;
    private formattedfields.FormattedIntegerField iXField;
    private formattedfields.FormattedIntegerField iYField;
    private formattedfields.FormattedIntegerField iZField;
    private javax.swing.JButton integerAddButton;
    private javax.swing.JPanel integerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private formattedfields.FormattedCurrencyField paymentField;
    private formattedfields.FormattedIntegerField periodsField;
    private formattedfields.FormattedPhoneField phoneField;
    private formattedfields.FormattedPercentField rateField;
    private formattedfields.FormattedSSNField ssnField;
    private formattedfields.FormattedDoubleField xField;
    private formattedfields.FormattedDoubleField yField;
    private formattedfields.FormattedDoubleField zField;
    // End of variables declaration//GEN-END:variables
}
